Numpy arrays

In [893]:
import numpy as np
arr_1d = np.array([1,2,3,4,4])
print("1D Array", arr_1d)

arr_2d = np.array([[1,2,3,4], [4,5,6,6]])
print("2D Array", arr_2d)

1D Array [1 2 3 4 4]
2D Array [[1 2 3 4]
 [4 5 6 6]]


List vs numpy arrays

In [894]:
py_list = [1,2,3,4]
print( "Python list multiplication " , py_list * 3)

np_arrays = np.array([1,2,3])
print( "Numpy array multiplication ", np_arrays * 3)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n multiplication list :", time.time() - start )

start = time.time()
np_arrays = np.arange(100000) * 2
print("\n Array multiplication: ", time.time() - start )

Python list multiplication  [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication  [3 6 9]

 multiplication list : 0.007846832275390625

 Array multiplication:  0.0003643035888671875


Creating array from scratch

In [895]:
zeros = np.zeros((2,3))
print("Zeros array \n ", zeros)

ones = np.ones((2,4))
print("Ones array \n", ones)

full = np.full((2,4),6)
print("Full array", full)

random = np.random.random((2,3))
print("Random array", random)

sequence = np.arange(0,11,2)
print("Squence array", sequence)

Zeros array 
  [[0. 0. 0.]
 [0. 0. 0.]]
Ones array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array [[6 6 6 6]
 [6 6 6 6]]
Random array [[0.03230613 0.97641082 0.76366087]
 [0.97663647 0.01926771 0.12523978]]
Squence array [ 0  2  4  6  8 10]


Vector, Matrix and Tensor

In [896]:
vector = np.array([1,2,3,4,5])
print("Vector: ", vector)

matrix = np.array([[1,2],
                  [3,4]])
print("Matrix:", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor:",tensor)

Vector:  [1 2 3 4 5]
Matrix: [[1 2]
 [3 4]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [897]:
arr =np.array([[1,2,3,],
               [4,5,6]])
print("shape:", arr.shape)
print("Dimension", arr.ndim)
print("size", arr.size)
print("Dtype", arr.dtype)


shape: (2, 3)
Dimension 2
size 6
Dtype int64


Reshaping Arrays

In [898]:
arr =np.arange(12)
print('orignal array \n ', arr)

reshaped = arr.reshape([3,4])
print("\n reshaped array:", reshaped)

flattend = reshaped.flatten()
print('\n flaten array  ', flattend)

resized = np.resize(reshaped, [2,3])
print("\n resize array", resized )

reveled = reshaped.ravel()
print("\n reveled array ", reveled)

orignal array 
  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flaten array   [ 0  1  2  3  4  5  6  7  8  9 10 11]

 resize array [[0 1 2]
 [3 4 5]]

 reveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


Numpy Array Operations

In [899]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("basic slicin", arr[2:6])
print("step slicing", arr[2:10:2])
print("negative:", arr[-4])

# 2d arrays
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [9,8,7]])
print("Rows and columns ", arr_2d[2, 0])
print("row", arr_2d[1])
print("columns ",arr_2d[:,0])

basic slicin [3 4 5 6]
step slicing [3 5 7 9]
negative: 7
Rows and columns  9
row [4 5 6]
columns  [1 4 9]


Sorting and Filter Arrays

In [900]:
unsorted = np.array([5,3,8,2,0,1,4,12,9,10])
print("sorted array: ", np.sort(unsorted))
arr_2d_sort = np.array([[3,6],[2,3],[5,4]])
print("sort column ", np.sort(arr_2d_sort, axis=0))

# filter arrays
number = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
even_num = number[number % 2 == 0]
print("Even number ", even_num)



sorted array:  [ 0  1  2  3  4  5  8  9 10 12]
sort column  [[2 3]
 [3 4]
 [5 6]]
Even number  [ 2  4  6  8 10 12]


In [901]:
# filter with mask
mask = number >5 
print("numbers: ", number[mask])

# indexing vs np.where
index = [1,2,3,4]
print(number[index])
where_r = np.where(number >5)
# print(where_r)
print("Np where", number[where_r])

numbers:  [ 6  7  8  9 10 11 12]
[2 3 4 5]
Np where [ 6  7  8  9 10 11 12]


In [902]:
condition_arr = np.where(number >5, number*3, number)
print(condition_arr)

arrs_2d = np.where(arr_2d >4, arr_2d*2, arr_2d)
print(arrs_2d)

[ 1  2  3  4  5 18 21 24 27 30 33 36]
[[ 1  2  3]
 [ 4 10 12]
 [18 16 14]]


Adding and removing data

In [903]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

combine = np.concatenate((arr1 , arr2)) 
print(combine)


[1 2 3 4 5 6 7 8]


Array compatibility

In [904]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

print(c.dtype == b.dtype)

True


In [905]:
org = np.array([[1,2],[3,4]])
n_row = np.array([5,6])
wn_row = np.vstack((org, n_row))
print(wn_row)

# add column
n_col = np.array([[9],[7]])
wn_col = np.hstack((org, n_col))
print(wn_col)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 9]
 [3 4 7]]


Array deletion